version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
  - package-ecosystem: "docker"
    directory: "/.github/actions/latest-wrangler"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
