name: Internal Archive Release

on:
  workflow_call:
    inputs:
      version_number:
        description: "The release version number (i.e. 1.0.0b1)"
        type: string
        required: true
      package_test_command:
        description: "Package test command"
        type: string
        required: true

jobs:
  job-setup:
    name: Job Setup
    runs-on: ubuntu-latest
    outputs:
      main_sha: ${{ steps.set_sha.outputs.main_sha }}
    steps:
      - name: "[DEBUG] Print Variables"
        run: |
          echo The release version number:         ${{ inputs.version_number }}
          echo Package test command:               ${{ inputs.package_test_command || '' }}

      - name: "Checkout main branch"
        uses: actions/checkout@v4
        with:
          ref: main

      # Will be the last sha on the main branch
      - name: "Capture sha"
        id: set_sha
        run: |
          echo "main_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
