name: Release package

on:
  workflow_dispatch:
    inputs:
      inputValidationStrategy:
        description: Pick how to validate inputs
        required: true
        type: choice
        default: sequential
        options:
          - sequential
          - all-at-once
      commitSHA:
        description: Commit to release
        required: true
        type: string
        default: ""
      packageVersion:
        description: Version to release
        required: true
        type: string
        default: ""
      buildScriptPath:
        description: Path to build scripts
        required: true
        type: string
        default: "scripts/build-dist.sh"

jobs:
  check-input-data:
    uses: dbt-labs/dbt-release/.github/workflows/release_pre_checks.yml@master
    with:
      commitSHA: ${{ github.event.inputs.commitSHA }}
      packageVersion: ${{ github.event.inputs.packageVersion }}
      continueOnError: ${{ github.event.inputs.inputValidationStrategy == 'all-at-once' }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  sources-unit-tests:
    uses: dbt-labs/dbt-release/.github/workflows/sources_unit_test.yml@master
    with:
      commitSHA: ${{ github.event.inputs.commitSHA }}

  generate-changelog-and-release-branch:
    runs-on: ubuntu-latest
    needs: sources-unit-tests
    steps:
      - name: Run ${{ github.job }}
        run: |
          echo "Place holder for ${{ github.job }}"

  package-build-and-test:
    needs: generate-changelog-and-release-branch
    uses: dbt-labs/dbt-release/.github/workflows/release_build_and_test.yml@master
    with:
      commitSHA: ${{ github.event.inputs.commitSHA }}
      packageVersion: ${{ github.event.inputs.packageVersion }}
      buildScriptPath: ${{ github.event.inputs.buildScriptPath }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  package-publish:
    runs-on: ubuntu-latest
    needs: package-build-and-test
    steps:
      - name: Run ${{ github.job }}
        run: |
          echo "Place holder for ${{ github.job }}"
