# **what?**
# Perform the version bump, generate the changelog and run tests.
#
# Inputs:
#  sha: the commit to attach to this release
#  version_number: version number for the release (ex: 1.2.3rc2)
#  target_branch: The branch that we will release from
#
# Outputs:
#   final_sha: The sha that will actually be released.  This can differ from the
#              input sha if adding a version bump and/or changelog
#   changelog_path: path to the changelog file (ex .changes/1.2.3-rc1.md)
#
# **why?**
# Reusable and consistent GitHub release process.
#
# **when?**
# Call when ready to kick off a build and release
#
# Validation Checks
#
#  1. Bump the version if it has not been bumped
#  2. Generate the changelog (via changie) if there is no markdown file for this version
#

name: Version Bump and Changelog Generation

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      version_number:
        required: true
        type: string
      target_branch:
        required: true
        type: string
      test_run:
        required: false
        default: true
        type: boolean
    outputs:
      final_sha:
        description: The new commit that includes the changelog and version bump.
        value: ${{ jobs.get-release-sha.outputs.final_sha }}
      changelog_path:
        description: The path to the changelog for this version
        value: ${{ jobs.audit-changelog.outputs.changelog_path }}

permissions:
  contents: write

env:
  PYTHON_TARGET_VERSION: 3.8
  NOTIFICATION_PREFIX: "[Release Preparation]"

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: "[DEBUG] Print Variables"
        run: |
          # WORKFLOW INPUTS
          echo The last commit sha in the release:   ${{ inputs.sha }}
          echo The release version number:           ${{ inputs.version_number }}
          echo The branch that we will release from: ${{ inputs.target_branch }}
          echo Test run:                             ${{ inputs.test_run }}
          # ENVIROMENT VARIABLES
          echo Python target version:                ${{ env.PYTHON_TARGET_VERSION }}
          echo Notification prefix:                  ${{ env.NOTIFICATION_PREFIX }}

  audit-changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog_path: ${{ steps.set_path.outputs.changelog_path }}
      exists: ${{ steps.set_existence.outputs.exists }}
      base_version: ${{ steps.semver.outputs.base-version }}
      prerelease: ${{ steps.semver.outputs.pre-release }}
      is_prerelease: ${{ steps.semver.outputs.is-pre-release }}

    steps:
      - name: "Checkout ${{ github.repository }} Commit ${{ inputs.sha }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}

      - name: "Audit Version And Parse Into Parts"
        id: semver
        uses: dbt-labs/actions/parse-semver@v1
        with:
          version: ${{ inputs.version_number }}

      - name: "Set Changelog Path"
        id: set_path
        run: |
          path=".changes/"
          if [[ ${{ steps.semver.outputs.is-pre-release }} -eq 1 ]]
          then
            path+="${{ steps.semver.outputs.base-version }}-${{ steps.semver.outputs.pre-release }}.md"
          else
            path+="{{ steps.semver.outputs.version }}.md"
          fi
          echo "changelog_path=$path" >> $GITHUB_OUTPUT

      - name: "Set Changelog Existence For Subsequent Jobs"
        id: set_existence
        run: |
          if test -f ${{ steps.set_path.outputs.changelog_path }}
          then
            echo "exists=true">> $GITHUB_OUTPUT
          else
            echo "exists=false">> $GITHUB_OUTPUT
          fi

      - name: "[DEBUG] Print Outputs"
        run: |
          echo changelog_path: ${{ steps.set_path.outputs.changelog_path }}
          echo exists:         ${{ steps.set_existence.outputs.exists }}
          echo base_version:   ${{ steps.semver.outputs.base-version }}
          echo prerelease:     ${{ steps.semver.outputs.pre-release }}
          echo is_prerelease:  ${{ steps.semver.outputs.is-pre-release }}

  audit-version-in-code:
    runs-on: ubuntu-latest
    outputs:
      up_to_date: ${{ steps.set_status.outputs.up_to_date }}

    steps:
      - name: "Checkout ${{ github.repository }} Commit ${{ inputs.sha }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}

      - name: "Check Current Version In Code"
        id: set_status
        run: |
          if grep -Fxq "current_version = ${{ inputs.version_number }}" .bumpversion.cfg
          then
            echo "up_to_date=true" >> $GITHUB_OUTPUT
          else
            echo "up_to_date=false" >> $GITHUB_OUTPUT
          fi

      - name: "[DEBUG] Print Outputs"
        run: |
          echo up_to_date: ${{ steps.set_status.outputs.up_to_date }}

  skip-generate-changelog:
    runs-on: ubuntu-latest
    needs: [audit-changelog]
    if: needs.audit-changelog.outputs.exists == 'true'

    steps:
      - name: "Changelog Exists, Skip Generating New Changelog"
        run: |
          echo A changelog file already exists at ${{ needs.audit-changelog.outputs.exists }}, skipping generating changelog

  skip-version-bump:
    runs-on: ubuntu-latest
    needs: [audit-version-in-code]
    if: needs.audit-version-in-code.outputs.up_to_date == 'true'

    steps:
      - name: "Version Already Bumped"
        run: |
          echo The version has already been bumped to ${{ inputs.version_number }}, skipping version bump

  create-temp-branch:
    outputs:
      branch_name: ${{ steps.variables.outputs.branch_name }}
    runs-on: ubuntu-latest
    needs: [audit-changelog, audit-version-in-code]
    if: needs.audit-changelog.outputs.exists == 'false' || needs.audit-version-in-code.outputs.up_to_date == 'false'

    steps:
      - name: "Checkout ${{ github.repository }} Commit ${{ inputs.sha }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}

      - name: "Generate Branch Name"
        id: variables
        run: |
          name="prep-release/"
          if [[ ${{ inputs.test_run }} == true ]]
          then
            name+="test-run/"
          fi
          name+="${{ inputs.version_number }}_$GITHUB_RUN_ID"
          echo "branch_name=$name" >> $GITHUB_OUTPUT

      - name: "Create Branch - ${{ steps.variables.outputs.branch_name }}"
        run: |
          git checkout -b ${{ steps.variables.outputs.branch_name }}
          git push -u origin ${{ steps.variables.outputs.branch_name }}

      - name: "[DEBUG] Print Outputs"
        run: |
          echo branch_name ${{ steps.variables.outputs.branch_name }}

  generate-changelog-bump-version:
    runs-on: ubuntu-latest
    needs: [audit-changelog, audit-version-in-code, create-temp-branch]

    steps:
      - name: "Checkout ${{ github.repository }} Branch ${{ needs.create-temp-branch.outputs.branch_name }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.create-temp-branch.outputs.branch_name }}

      - name: "Add Homebrew To PATH"
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: "Install Spark Dependencies"
        if: ${{ github.repository == 'dbt-labs/dbt-spark' }}
        run: |
          sudo apt-get install libsasl2-dev

      - name: "Install Homebrew Packages"
        run: |
          brew install pre-commit
          brew tap miniscruff/changie https://github.com/miniscruff/changie
          brew install changie

      - name: "Generate Release Changelog"
        if: needs.audit-changelog.outputs.exists == 'false'
        run: |
          if [[ ${{ needs.audit-changelog.outputs.is_prerelease }} -eq 1 ]]
          then
            changie batch ${{ needs.audit-changelog.outputs.base_version }} --move-dir '${{ needs.audit-changelog.outputs.base_version }}' --prerelease ${{ needs.audit-changelog.outputs.prerelease }}
          else
            changie batch ${{ needs.audit-changelog.outputs.base_version }}  --include '${{ needs.audit-changelog.outputs.base_version }}' --remove-prereleases
          fi
          changie merge
          git status

      # this step will fail on whitespace errors but also correct them
      - name: "Remove Trailing Whitespace Via Pre-commit"
        continue-on-error: true
        run: |
          pre-commit run trailing-whitespace --files .bumpversion.cfg CHANGELOG.md .changes/*
          git status

      # this step will fail on newline errors but also correct them
      - name: "Removing Extra Newlines Via Pre-commit"
        continue-on-error: true
        run: |
          pre-commit run end-of-file-fixer --files .bumpversion.cfg CHANGELOG.md .changes/*
          git status

      - name: "Check Changelog Created Successfully"
        if: needs.audit-changelog.outputs.exists == 'false'
        run: |
          if [[ -f ${{ needs.audit-changelog.outputs.changelog_path }} ]]
          then
            echo Changelog file created successfully
          else
            echo Changelog failed to generate.  Exiting.
            exit 1
          fi

      - name: "Set up Python - ${{ env.PYTHON_TARGET_VERSION }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_TARGET_VERSION }}

      - name: "Install Python Dependencies"
        if: needs.audit-version-in-code.outputs.up_to_date == 'false'
        run: |
          python3 -m venv env
          source env/bin/activate
          python -m pip install --upgrade pip

      - name: "Bump Version To ${{ inputs.version_number }}"
        if: needs.audit-version-in-code.outputs.up_to_date == 'false'
        # note: bumpversion is no longer supported, it actually points to bump2version now
        run: |
          source env/bin/activate
          python -m pip install -r dev-requirements.txt
          env/bin/bumpversion --allow-dirty --new-version ${{ inputs.version_number }} major
          git status

      - name: "Commit & Push Changes"
        run: |
          #Data for commit
          user="Github Build Bot"
          email="buildbot@fishtownanalytics.com"
          commit_message="Bumping version to ${{ inputs.version_number }} and generate changelog"
          #Commit changes to branch
          git config user.name "$user"
          git config user.email "$email"
          git pull
          git add .
          git commit -m "$commit_message"
          git push

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: [create-temp-branch, generate-changelog-bump-version]

    env:
      TOXENV: unit

    steps:
      - name: "Checkout ${{ github.repository }} Branch ${{ needs.create-temp-branch.outputs.branch_name }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.create-temp-branch.outputs.branch_name }}

      - name: "Set up Python - ${{ env.PYTHON_TARGET_VERSION }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_TARGET_VERSION }}

      - name: "Install Python Dependencies"
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install tox
          python -m pip --version
          python -m tox --version

      - name: "Run Tox"
        run: tox

  # run-integration-tests:
  #   runs-on: ubuntu-latest
  #   needs: [create-temp-branch, generate-changelog-bump-version]

  #   env:
  #     TOXENV: integration

  #   steps:
  #     - name: "Checkout ${{ github.repository }} Branch ${{ needs.create-temp-branch.outputs.branch_name }}"
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ needs.create-temp-branch.outputs.branch_name }}

  #     - name: "Set up Python - ${{ env.PYTHON_TARGET_VERSION }}"
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ env.PYTHON_TARGET_VERSION }}

  #     - name: "Install python tools"
  #       run: |
  #         python -m pip install --user --upgrade pip
  #         python -m pip --version
  #         python -m pip install tox
  #         tox --version

  #     - name: Run tests
  #       run: tox

  merge-changes-into-target-branch:
    runs-on: ubuntu-latest
    needs: [run-unit-tests, create-temp-branch]
    if: ${{ inputs.test_run == false }}

    steps:
      - name: "[Debug] Print Variables"
        run: |
          echo target_branch: ${{ inputs.target_branch }}
          echo branch_name:   ${{ needs.create-temp-branch.outputs.branch_name }}

      - name: "Checkout Repo ${{ github.repository }}"
        uses: actions/checkout@v3

      - name: "Merge Changes Into ${{ inputs.target_branch }}"
        uses: everlytic/branch-merge@1.1.2
        with:
          source_ref: ${{ needs.create-temp-branch.outputs.branch_name }}
          target_branch: ${{ inputs.target_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }} # TODO: probably need to use a custom PAT to override ``.latest`` protection rules
          commit_message_template: "[Automated] Merged {source_ref} into target {target_branch} during release process"

  get-release-sha:
    # Get the sha that will be released.  If the changelog already exists on the input sha and the version has already been bumped,
    # then it is what we will release. Otherwise we generated a changelog and did the version bump in this workflow and there is a
    # new sha to use from the merge we just did.  Grab that here instead.
    outputs:
      final_sha: ${{ steps.final_sha.outputs.final_sha }}
    runs-on: ubuntu-latest
    needs:
      [
        create-temp-branch,
        merge-changes-into-target-branch,
        audit-changelog,
        audit-version-in-code,
      ]
    # always run this job, regardness of if the dependant jobs were skipped
    if: always()

    steps:
      - name: "[Debug] Print Variables"
        run: |
          echo target_branch:    ${{ inputs.target_branch }}
          echo new_branch:       ${{ needs.create-temp-branch.outputs.branch_name }}
          echo changelog_exists: ${{ needs.audit-changelog.outputs.exists }}
          echo up_to_date:       ${{ needs.audit-version-in-code.outputs.up_to_date }}

      - name: "Resolve Branch To Checkout"
        id: resolve_branch
        run: |
          branch=""
          if [[ ${{ inputs.test_run == true }} ]]
          then
            branch=${{ needs.create-temp-branch.outputs.branch_name }}
          else
            branch=${{ inputs.target_branch }}
          fi
          echo "target_branch=$branch" >> $GITHUB_OUTPUT

      - name: "Check Out Target Branch - ${{ steps.resolve_branch.outputs.target_branch  }}"
        if: ${{ inputs.test_run == false }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target_branch }}

      - name: "[Debug] Log Branch"
        run: git status

      - name: "Resolve Commit SHA For Release"
        id: final_sha
        run: |
          commit_sha=""
          if [[ ${{ needs.audit-changelog.outputs.exists }} == false ]] || [[ ${{ needs.audit-version-in-code.outputs.up_to_date }} == false ]]
          then
            commit_sha=$(git rev-parse HEAD)
          else
            commit_sha=${{ inputs.sha }}
          fi
          echo "final_sha=$commit_sha" >> $GITHUB_OUTPUT

      - name: "Remove Temp Branch - ${{ needs.create-temp-branch.outputs.branch_name }}"
        if: ${{ inputs.test_run == false && needs.create-temp-branch.outputs.branch_name != '' }}
        run: |
          git push origin -d ${{ needs.create-temp-branch.outputs.branch_name }}

      - name: "[Debug] Print Outputs"
        run: |
          echo final_sha: ${{ steps.final_sha.outputs.final_sha }}
