name: test dbt releases
# placeholder workflow for tests and possibly nightly builds

on:
  push:
    paths-ignore:
      - releases/**

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
